# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TealiumContentsquareExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumContentsquareExample
  # pod "TealiumContentsquare", :path => "../"
  pod "tealium-swift", :path=> "/Users/christina/Projects/work-repos/github/tealium-swift-builder"
  pod 'CS_iOS_SDK'
end
